name: Build workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the git repo
        uses: actions/checkout@v4

      - name: Build the code
        run: make

      - name: Executable
        uses: actions/upload-artifact@v4
        with:
          name: exec
          path: exec
  
